steps:
  - label: ":julia: Run tests on 1.6 LTS"
    plugins:
      - JuliaCI/julia#v1:
          version: 1.6
      - JuliaCI/julia-test#v1:
          use_ssh: true
          julia_args: "-e \"import Pkg; Pkg.build()\""
    if: build.message !~ /\[skip tests\]/
    timeout_in_minutes: 120
    artifact_paths:
      - "test/logs/*.pdf"